### PR TITLE
Gf mastering: v1.200

### PR DESCRIPTION
**Pull request by m4rc1e**
Hey Dave,

I've had to rebuild this repository based on the vfbs you provided me.

I've tried to stay as faithful to the original as possible.

We have no missing glyphs and the only visible modification fixes, https://github.com/google/fonts/issues/133

caveat-rupee

The rendering has changed because the old version was hinted with ttfautohint v1.3. The changes are only noticeable under 18pt.
caveat-hinting

Once you're happy and this is merged, I'll send a pr to google/fonts

### CODE REVIEW

**Comment by davelab6** [comment]
I don't know what music you were listening to today but the timing in that
gif is wacky 😂

I filed https://github.com/m4rc1e/gfregression/issues/12 because it was
hard for me to see which state was which.

I suspect the ttfautohint delta can be reduced with some x height snapping
settings which I think had the defaults changed since then.

**Comment by m4rc1e** [comment]
> I suspect the ttfautohint delta can be reduced with some x height snapping
settings which I think had the defaults changed since then. 

The project was originally autohinted with ttfautohint v1.3. The update uses the latest, v1.6. I have played with the settings to get them to match as close as possible. I've been proofing on Win 10 IE 11.

Here's another take at that screenshot.

**Regular**
caveat-reg-waterfall
caveat-reg-waterfall-2


**Bold**
caveat-bd-waterfall
caveat-bd-waterfall-2

**Comment by davelab6** [comment]
Ttfautohint v1.7 was released a few days ago :)

**Comment by davelab6** [comment]
I can't look at these screenshots with target/base on the right side of the page. I need it next to the pt size label.

**Comment by davelab6** [comment]
The label text also isn't totally clear to me. I think "API" or "live" or "current", and "PR" or "testing" or "update" would be better

**Comment by davelab6** [comment]
I'm going to merge this since the repo is empty :)

**Comment by davelab6** [comment]
Commit history looks great btw, good stuff :)

**Pull request merged**
