### PR TITLE
VF upgrade

### PR DESCRIPTION
**Pull request by m4rc1e**

### CODE REVIEW

**Comment by m4rc1e** [comment]
@davelab6 please merge this. I don't have permission.

**Comment by pichotta** [comment]
@googlebot I fixed it.

**Comment by djrrb** [comment]
@googlebot I consent.

**Comment by pichotta** [comment]
@googlebot I consent.

**Comment by victoriaalissia** [comment]
@googlebot I consent.

**Comment by moyogo** [comment]
@googlebot I consent.

**Comment by victoriaalissia** [comment]
@googlebot I fixed it.

**Comment by davelab6** [comment]
@victoriaalissia I think your commits above were done as `Victoria Rushton <hello@victoriarushton.com>` but that email seems to not be associated with your Github account, and that's why the bot didn't find the CLA entry. Not sure, but please could you check? :)

**Comment by victoriaalissia** [comment]
hi @davelab6, that's really weird! i've added hello@victoriarushton.com to my github account but can't re-sign the CLA or edit my contact info there, let me know what i can try next :)
screen_shot_2020-10-15_at_1 51 24_pm

**Pull request merged**
